# ======================================================================================================================================== #
# ============================================================= DEPENDENCIES ============================================================= #
# ======================================================================================================================================== #

UniLib.verify_version(0.7, __FILE__)

# ======================================================================================================================================== #
# ============================================================== PUBLIC API ============================================================== #
# ======================================================================================================================================== #

# AMPHAROS_CREST = Reborn ? :AMPHAROSCREST : :AEAMPHCREST

ARIADOS_CREST = Reborn ? :ARIADOSCREST : :ARIACREST

BASTIODON_CREST = Reborn ? :BASTIODONCREST : :BASTCREST

BEHEEYEM_CREST = Reborn ? :BEHEEYEMCREST : :BEHECREST

# BOLTUND_CREST = Reborn ? :BOLTUNDCREST : :BOLTCREST

CASTFORM_CREST = Reborn ? :CASTFORMCREST : :CASTCREST

CHERRIM_CREST = Reborn ? :CHERRIMCREST : :CHERCREST

CINCCINO_CREST = Reborn ? :CINCCINOCREST : :CINCCREST

CLAYDOL_CREST = Reborn ? :CLAYDOLCREST : :CLAYCREST

COFAGRIGUS_CREST = Reborn ? :COFAGRIGUSCREST : :COFCREST

CRABOMINABLE_CREST = Reborn ? :CRABOMINABLECREST : :CRABCREST

CRYOGONAL_CREST = Reborn ? :CRYOGONALCREST : :CRYCREST

DARMANITAN_CREST = Reborn ? :DARMANITANCREST : :DARMCREST

DEDENNE_CREST = Reborn ? :DEDENNECREST : :DEDECREST

DELCATTY_CREST = Reborn ? :DELCATTYCREST : :DELCREST

DRUDDIGON_CREST = Reborn ? :DRUDDIGONCREST : :DRUDDICREST

DUSKNOIR_CREST = Reborn ? :DUSKNOIRCREST : :DUSKCREST

ELECTRODE_CREST = Reborn ? :ELECTRODECREST : :ELECCREST

EMPOLEON_CREST = Reborn ? :EMPOLEONCREST : :EMPCREST

FEAROW_CREST = Reborn ? :FEAROWCREST : :FEARCREST

FERALIGATR_CREST = Reborn ? :FERALIGATRCREST : :FERACREST

FURRET_CREST = Reborn ? :FURRETCREST : :FURRCREST

GLACEON_CREST = Reborn ? :GLACEONCREST : :GLACCREST

GOTHITELLE_CREST = Reborn ? :GOTHITELLECREST : :GOTHCREST

HYPNO_CREST = Reborn ? :HYPNOCREST : :HYPCREST

INFERNAPE_CREST = Reborn ? :INFERNAPECREST : :INFCREST

LEAFEON_CREST = Reborn ? :LEAFEONCREST : :LEAFCREST

LEDIAN_CREST = Reborn ? :LEDIANCREST : :LEDICREST

LUVDISC_CREST = Reborn ? :LUVDISCCREST : :LUVCREST

LUXRAY_CREST = Reborn ? :LUXRAYCREST : :LUXCREST

MAGCARGO_CREST = Reborn ? :MAGCARGOCREST : :MAGCREST

MEGANIUM_CREST = Reborn ? :MEGANIUMCREST : :MEGCREST

NOCTOWL_CREST = Reborn ? :NOCTOWLCREST : :NOCCREST

ORICORIO_CREST = Reborn ? :ORICORIOCREST : :ORICREST

PHIONE_CREST = Reborn ? :PHIONECREST : :PHIONECREST

PROBOPASS_CREST = Reborn ? :PROBOPASSCREST : :PROBOCREST

RAMPARDOS_CREST = Reborn ? :RAMPARDOSCREST : :RAMPCREST

RELICANTH_CREST = Reborn ? :RELICANTHCREST : :RELICREST

REUNICLUS_CREST = Reborn ? :REUNICLUSCREST : :REUNICREST

SAMUROTT_CREST = Reborn ? :SAMUROTTCREST : :SAMUCREST

SAWSBUCK_CREST = Reborn ? :SAWSBUCKCREST : :SAWSCREST

SEVIPER_CREST = Reborn ? :SEVIPERCREST : :SEVCREST

SHIINOTIC_CREST = Reborn ? :SHIINOTICCREST : :SHIINCREST

SILVALLY_CREST = Reborn ? :SILVALLYCREST : :SILVCREST

SIMIPOUR_CREST = Reborn ? :SIMIPOURCREST : :POURCREST

SIMISAGE_CREST = Reborn ? :SIMISAGECREST : :SAGECREST

SIMISEAR_CREST = Reborn ? :SIMISEARCREST : :SEARCREST

SKUNTANK_CREST = Reborn ? :SKUNTANKCREST : :SKUNCREST

SPIRITOMB_CREST = Reborn ? :SPIRITOMBCREST : :SPIRITCREST

STANTLER_CREST = Reborn ? :STANTLERCREST : :STANTCREST

SWALOT_CREST = Reborn ? :SWALOTCREST : :SWACREST

# THIEVUL_CREST = Reborn ? :THIEVULCREST : :THIEVCREST

TORTERRA_CREST = Reborn ? :TORTERRACREST : :TORCREST

TYPHLOSION_CREST = Reborn ? :TYPHLOSIONCREST : :TYPHCREST

VESPIQUEN_CREST = Reborn ? :VESPIQUENCREST : :VESPICREST

WHISCASH_CREST = Reborn ? :WHISCASHCREST : :WHISCREST

ZANGOOSE_CREST = Reborn ? :ZANGOOSECREST : :ZANGCREST

ZOROARK_CREST = Reborn ? :ZOROARKCREST : :ZOROCREST
